# Generated by Django 3.1.12 on 2025-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_staff',
            field=models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Enable')], default=0),
        ),
    ]
