# Generated by Django 3.1.12 on 2025-02-09 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0005_employee_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendance',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
