# Generated by Django 3.1.12 on 2025-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='sent_status',
            field=models.SmallIntegerField(choices=[(0, 'Not Sent'), (1, 'Sent')], default=0),
        ),
    ]
